mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # \u5982\u679C\u9700\u8981\u7528 hikari\uFF0C\u9700\u8981\u914D\u7F6E hikari
  #spring.datasource.hikari.jdbc-url=jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time?useUnicode=true&useSSL=false&characterEncoding=utf8
  #spring.datasource.data-username=root
  #spring.datasource.data-password=Liub630918
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

spring:
  datasource:
    url: jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Liub630918
    driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    root: DEBUG
