spring:
    application:
        name: other


    profiles:
        active: dev

    datasource:
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            maximum-pool-size: 100
            pool-name: HikaraPool-1
            minimum-idle: 10
        password: 123456
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:33062/salve_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&

mybatis-plus:
    # 搜索指定包别名
    type-aliases-package: com.example.other
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true


