

server:
  port: 8081

dubbo:
  registry:
    address: nacos://127.0.0.1:18848
  application:
    name: dubbo-protocol-example-customer-1
  protocol:
    name: dubbo
    port: 12181
  consumer:
    # 如果出现了调用循环依赖时可以关闭 调用端启动检查  （检查是否有提供者服务）
    check: false


