dubbo:
    registry:
        address: nacos://127.0.0.1:18848
        port: 20881
#        instance/interface/all
        register-mode: interface
    consumer:
        connections: 10
    protocol:
        name: tri
        port: 50051
server:
    port: 14010
spring:
    application:
        name: dubbo-provider-one
    datasource:
        hikari:
            auto-commit: true
            minimum-idle: 30
            maximum-pool-size: 200
            idle-timeout: 30000
            connection-timeout: 30000
            validation-timeout: 10000
            timeout: 60000
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:33061/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource




mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
        cache-enabled: false


