server:
  port: 9002
spring:
  application:
    name: order-service

# 远程地址
#zipkin
  zipkin:
    base-url: http://localhost:9411/
    # 让nacos把它当成一个url，而不是要当成服务名
    discoveryClientEnabled: false
    # 设置使用http的方式传输数据
    sender:
      type: web
    enable: true
  #采样的百分比
  sleuth:
    web:
      client:
        enabled: true
    # 采样比例为: 0.1(即10%),设置的值介于0.0到1.0之间，1.0则表示全部采集。
    sampler:
      probability: 1.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: order-service-9002



service:
  payment:
    url: payment-service
    getPayment: http://${service.payment.url}/payment/get



