mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #spring.datasource.hikari.jdbc-url=jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time?useUnicode=true&useSSL=false&characterEncoding=utf8
  #spring.datasource.data-username=root
  #spring.datasource.data-password=Liub630918
spring:
  datasource:
    url: jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Liub630918
    driver-class-name: com.mysql.cj.jdbc.Driver

    dynamic:
      datasource:
        master-1:
          url: jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time?useUnicode=true&useSSL=false&characterEncoding=utf8
          username: root
          password: Liub630918
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time_slave_1?useUnicode=true&useSSL=false&characterEncoding=utf8
          username: root
          password: Liub630918
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://rm-bp14z2vanu1hlt59rao.mysql.rds.aliyuncs.com:3306/time_slave_2?useUnicode=true&useSSL=false&characterEncoding=utf8
          username: root
          password: Liub630918
          driver-class-name: com.mysql.cj.jdbc.Driver
      primary: master-1

  redis:
    database: 1
    host: 127.0.0.1
    port: 16379
    repositories:
      enabled: true
  #management.endpoint.health.enabled=true

logging:
  level:
    root: DEBUG
