spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: MyBatis-Plus-Pool
#      jdbc-url: jdbc:mysql://localhost:33061/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      maximum-pool-size: 10

  sleuth:
    enabled: true
    trace-id128: false
    sampler:
      rate: 100
      probability: 1.0
  application:
    name: mybatis-plus-example
  zipkin:
    sender:
      type: web
      base-url: http://localhost:9411
      enable: true




mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false
logging:
  level:
    com.example: DEBUG
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(${LOG_CORRELATION_PATTERN:- }){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(${LOG_CORRELATION_PATTERN:- }){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

#    correlation: "%clr([%X{X-B3-TraceId},${correlationId}]){blue}"
