spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: MyBatis-Plus-Pool
#      jdbc-url: jdbc:mysql://localhost:33061/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      maximum-pool-size: 10



mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false
logging:
  level:
    com.example.mybatisplusexample: debug

